.bumpversion.cfg
.ci/run_container.sh
.github/workflows/main.yml
.github/workflows/nightly.yml
setup.py

Update CI files

---

.ci/scripts/validate_commit_message.py
CHANGES/5.feature
pulpcore/cli/ostree/__init__.py
pulpcore/cli/ostree/context.py
pulpcore/cli/ostree/distribution.py
pulpcore/cli/ostree/remote.py
pulpcore/cli/ostree/repository.py
tests/conftest.py
tests/scripts/pulp_ostree/test_import_publish.sh
tests/scripts/pulp_ostree/test_sync_publish.sh

Add the CLI for pulp_ostree

---

pulpcore/cli/ostree/context.py
pulpcore/cli/ostree/repository.py
tests/scripts/pulp_ostree/test_import_publish.sh
tests/scripts/pulp_ostree/test_modify_content.sh
tests/scripts/pulp_ostree/test_sync_publish.sh

Add CLI for the modify endpoint

---

.ci/run_container.sh

Rename pulp-cli-deb default branch to main

---

.ci/assets/Containerfile.source
tests/scripts/pulp_ostree/test_modify_content.sh

Update the reference to the default branch

---

.github/workflows/main.yml
.github/workflows/nightly.yml
pulpcore/cli/ostree/repository.py
setup.py
test_requirements.txt
tests/scripts/pulp_ostree/test_import_publish.sh
tests/scripts/pulp_ostree/test_modify_content.sh

Deprecate the reference to a parent commit

---

.ci/assets/Containerfile
.ci/assets/Containerfile.source
.ci/run_container.sh

Use ghcr images

---

CHANGES/14.feature
pulpcore/cli/ostree/context.py
pulpcore/cli/ostree/repository.py
tests/scripts/pulp_ostree/test_modify_content.sh

Add support for modifying config files

---

CHANGES/16.feature
pulpcore/cli/ostree/context.py
pulpcore/cli/ostree/remote.py
tests/scripts/pulp_ostree/test_sync_publish.sh

Add support for filtering refs within a remote

---

CHANGES/19.feature
pulpcore/cli/ostree/context.py
pulpcore/cli/ostree/repository.py
tests/scripts/pulp_ostree/test_import_publish.sh

Decouple workflows for importing refs and commits

---

CHANGES.md

Add missing versions

---

.github/dependabot.yml
.github/workflows/main.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
pulpcore/cli/ostree/__init__.py
pulpcore/cli/ostree/distribution.py
pulpcore/cli/ostree/remote.py
pulpcore/cli/ostree/repository.py
setup.py

* Bump pulp-cli dependency to 0.15.0.
* Use forward compatible import paths from pulp-cli.
* Update test matrix.
[noissue]

Update the codebase

---

.ci/assets/Containerfile.source
.ci/scripts/validate_commit_message.py
.github/workflows/main.yml
.github/workflows/nightly.yml
pyproject.toml
setup.py

Test the CLI with pulp-cli 0.17

---

.github/workflows/nightly.yml

Use custom Containerfile when running nightly builds

---

.github/workflows/release.yml

Update the release pipeline

---

.github/workflows/release.yml

Remove the docs publishing step

---

.github/workflows/test.yml

Fix CI issues by installing ostreelibs

---

.github/workflows/test.yml
lower_bounds_constraints.lock
pulp-glue-ostree/setup.py
setup.py

Bump the pulp-cli version

---

.ci/scripts/collect_changes.py
.ci/scripts/create_release_branch.sh
.ci/scripts/release.sh
.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/collect_changes.yml
.github/workflows/nightly.yml
.github/workflows/pr.yml
.github/workflows/pr_checks.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/release_branch.yml
.github/workflows/test.yml
CHANGES/.TEMPLATE.md
Makefile
pyproject.toml
test_requirements.txt

Setup and apply CI template

---

.ci/scripts/create_release_branch.sh

Fix changelog snippet removal

---

pulp-glue-ostree/pyproject.toml

Bump up the pulp-glue boundary
